name: Building Docker images

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        mpi: [openmpi, mpich]
        os: [ubuntu, debian]

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[main skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./${{ matrix.os }}/Dockerfile
          target: ${{ matrix.os }}_${{ matrix.cc }}_${{ matrix.mpi }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scientific_development_env:${{ matrix.os }}_${{ matrix.cc }}_${{ matrix.mpi }}
          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/scientific_development_env:${{ matrix.os }}_${{ matrix.cc }}_${{ matrix.mpi }}
          build-args: BUILDKIT_INLINE_CACHE=1
